name: EnhancedTextDisplays
version: '1.0'
main: org.mrdarkimc.enhancedtextdisplays.EnhancedTextDisplays
api-version: '1.19'
softdepend:
  - ItemsAdder
  - ajLeaderboards
  - PlaceholdersAPI
commands:
  try:
    description: Main plugin command
